### PR TITLE
Fix broken links to assets.  Fixes #359.

### LINKED ISSUE #359: Rdoc does not serve darkfish CSS
Hi,

I'm running on Fedora 22, and when I run `ri --serve` the generated rdoc requests `/css/rdoc.css` which the WEBrick servlet cannot find.

My procedure to reproduce is

1. `sudo dnf install ruby-devel rubygem-rdoc`
2. `gem install highline --ri --rdoc`
3. `ri --serve`

When I go to localhost:8214, the page is served but the CSS cannot be found.  Here are the relevant messages from WEBrick

```
[2015-07-31 11:42:41] INFO  WEBrick 1.3.1
[2015-07-31 11:42:41] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
[2015-07-31 11:42:41] INFO  WEBrick::HTTPServer#start: pid=3552 port=8214
localhost.localdomain - - [31/Jul/2015:11:42:56 EDT] "GET / HTTP/1.1" 200 3200
- -> /
localhost.localdomain - - [31/Jul/2015:11:43:01 EDT] "GET /css/fonts.css HTTP/1.1" 404 2048
http://localhost:8214/ -> /css/fonts.css
localhost.localdomain - - [31/Jul/2015:11:43:01 EDT] "GET /css/rdoc.css HTTP/1.1" 404 2048
http://localhost:8214/ -> /css/rdoc.css
localhost.localdomain - - [31/Jul/2015:11:43:01 EDT] "GET /js/search_index.js HTTP/1.1" 200 361
http://localhost:8214/ -> /js/search_index.js
localhost.localdomain - - [31/Jul/2015:11:43:01 EDT] "GET /favicon.ico HTTP/1.1" 404 2056
- -> /favicon.ico
```

I see in the [darkfish template](https://github.com/rdoc/rdoc/blob/master/lib/rdoc/generator/template/darkfish/_head.rhtml#L13) that the CSS is being served off `css/rdoc.css`, but in the [servlet.rb](https://github.com/rdoc/rdoc/blob/master/lib/rdoc/servlet.rb#L117), the case statement is matching on `/rdoc.css`

There are also some problems with the JS when I request the rdoc for an actual gem:

```
localhost.localdomain - - [31/Jul/2015:11:52:02 EDT] "GET /highline-1.7.2/js/navigation.js HTTP/1.1" 404 3912
http://localhost:8214/highline-1.7.2/ -> /highline-1.7.2/js/navigation.js
localhost.localdomain - - [31/Jul/2015:11:52:02 EDT] "GET /highline-1.7.2/js/searcher.js HTTP/1.1" 404 3910
localhost.localdomain - - [31/Jul/2015:11:52:02 EDT] "GET /highline-1.7.2/js/search.js HTTP/1.1" 404 3908
```

### PR DESCRIPTION
**Pull request by awood**

### CODE REVIEW

**Comment by awood** [comment]
This patch isn't 100% perfect: the CSS is still missing when the request 404s.  `generate_servlet_not_found` method in `generator.rb` isn't setting the `rel_prefix` but I'm not familiar enough with the code-base to say whether it should be or whether a 404 requires some other special handling.

**Comment by awood** [comment]
Travis isn't displaying the failing check to me.  All the tests are passing and 4cac2b5 is only a change to the Javascript.  If someone will tell me what the failing check is, I will be happy to fix it.  Also, if someone can answer my question about the `generate_servlet_not_found` method, I'd be happy to fix it too.

**Comment by awood** [comment]
Running Travis on my fork reveals the below failure in ruby-head version.  So I don't think this PR is actually the source of the problem.

```
1) Failure:
TestRDocMarkupToHtml#test_parseable_eh [/home/travis/build/awood/rdoc/test/test_rdoc_markup_to_html.rb:646]:

invalid syntax considered valid: class C end`
```

**Comment by awood** [comment]
The test failure is in `TestRDocMarkupToHtml#test_parseable_eh` against Ruby HEAD.  This PR doesn't touch any code related to that, so in my opinion the failure is a false positive.

**Comment by awood** [comment]
Anyone have any comments on this?  I'd love to see it make it into an upcoming release.

**Comment by zzak** [comment]
I'm not sure about the js and font changes though

**Comment by awood** [comment]
@zzak I'm a little unclear about your last comment.  Is there something I should address in the PR or is it more of a general "I want someone else to look at this too"?

**Comment by zzak** [comment]
@awood I tested out, and seems like everything is working!

Thank you! <3 <3

**Comment by awood** [comment]
:smiley_cat: :gem: :moneybag:

**Comment by MarioRuiz** [comment]
when is this fixed gonna be released? no new releases since february and this bug is not very nice to show when running a gem server on Ruby 2.2.4 "GET /doc_root/css/fonts.css HTTP/1.1" 404 2048
so any idea?

**Pull request merged**
